#:kivy 2.0.0

<screen_manager>:
    SelectionScreen:
        AnchorLayout:
            orientation: "horizontal"
            anchor_x: "center"
            anchor_y: "center"
            display: token_input

            TokenInput:
                id: token_input
                text: "cryptocurrency"
                multiline: False
                focus: True
                #text: TokenInput.on_text(self.text)
                on_text_validation: TokenInput.on_enter(self.text)